#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond.sh)

# Check if the PID was found
if [ -n "$pid" ]; then
    # Send a signal to terminate the process
    kill "$pid"
    echo "Terminated the 4-to_infinity_and_beyond process."
else
    echo "Process not found."
fi
